### ISSUE TITLE
怎么做到像UIAlertView那样让键盘收回

### ISSUE THREAD

**Issue by f2yu** [Bruce-7/HDAlertView#1]

**Comment by Bruce-7** [comment]
自己控制要弹出来, 就让键盘收回不就行了? 是这个意思?

**Comment by f2yu** [comment]
但是必须在代码之外去控制，不能像UIAlertView那样不在外部控制吗

**Comment by Bruce-7** [comment]
也可以的, 根据自己需求更改代码即可, 要show的时候就退出键盘, 要移除的时候就弹回键盘.
