### ISSUE TITLE
HDAlertView中返回buttonIndex错误

### ISSUE THREAD

**Issue by wangzzcloud** [Bruce-7/HDAlertView#3]
源代码：   
    for (int i = 0; i < otherButtonTitles.count; i++) {
        [alertView addButtonWithTitle:otherButtonTitles[i] type:HDAlertViewButtonTypeDefault handler:^(HDAlertView *alertView) {
            if (block) {
                if (!HDStringIsEmpty(cancelButtonTitle)) {
                    block(alertView, i + 1);
                }
                block(alertView, i);
            }
        }];
    }
改为：
 for (int i = 0; i < otherButtonTitles.count; i++) {
        [alertView addButtonWithTitle:otherButtonTitles[i] type:HDAlertViewButtonTypeDefault handler:^(HDAlertView *alertView) {
            if (block) {
                if (!HDStringIsEmpty(cancelButtonTitle)) {
                    block(alertView, i + 1);
                }else {
                    block(alertView, i);
                }
            }
        }];
    }

**Comment by Bruce-7** [comment]
十分感谢指出问题。这个是随手给个例子封装，可以按自己需求对HDAlertView进行封装。
