### ISSUE TITLE
整个控制器被销毁

### ISSUE THREAD

**Issue by vitasapple** [Bruce-7/HDAlertView#6]
我一直用这个，但是在最进的一个项目里，写了下面这段代码，整个控制器就被销毁，白屏。。。话说这个我都用很久了为什么会这样
HDAlertView *alertView = [HDAlertView alertViewWithTitle:@"温馨提示" andMessage:@"请在系统设置中开启定位服务(设置>隐私>定位服务>开启)"];
                
                [alertView addButtonWithTitle:@"cancel" type:HDAlertViewButtonTypeDefault handler:^(HDAlertView *alertView) {
                }];
                [alertView show];

**Comment by Bruce-7** [comment]
用的最新更新的代码吗？报的什么错?

**Comment by Bruce-7** [comment]
可能别的问题原因。
